// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { BulkUnlockData, BulkUnlockError, BulkUnlockResponse, LockContentData, LockContentError, LockContentResponse, LockOverviewError, LockOverviewResponse, StatusData, StatusError, StatusResponse, UnlockContentData, UnlockContentError, UnlockContentResponse } from './types.gen';

export const client = createClient(createConfig());

export class ContentLockService {
    public static bulkUnlock<ThrowOnError extends boolean = false>(options?: Options<BulkUnlockData, ThrowOnError>) {
        return (options?.client ?? client).post<BulkUnlockResponse, BulkUnlockError, ThrowOnError>({
            ...options,
            url: '/umbraco/contentlock/api/v1/ContentGuard/BulkUnlock'
        });
    }
    
    public static lockContent<ThrowOnError extends boolean = false>(options: Options<LockContentData, ThrowOnError>) {
        return (options?.client ?? client).get<LockContentResponse, LockContentError, ThrowOnError>({
            ...options,
            url: '/umbraco/contentlock/api/v1/ContentGuard/Lock/{key}'
        });
    }
    
    public static lockOverview<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<LockOverviewResponse, LockOverviewError, ThrowOnError>({
            ...options,
            url: '/umbraco/contentlock/api/v1/ContentGuard/LockOverview'
        });
    }
    
    public static status<ThrowOnError extends boolean = false>(options: Options<StatusData, ThrowOnError>) {
        return (options?.client ?? client).get<StatusResponse, StatusError, ThrowOnError>({
            ...options,
            url: '/umbraco/contentlock/api/v1/ContentGuard/Status/{key}'
        });
    }
    
    public static unlockContent<ThrowOnError extends boolean = false>(options: Options<UnlockContentData, ThrowOnError>) {
        return (options?.client ?? client).get<UnlockContentResponse, UnlockContentError, ThrowOnError>({
            ...options,
            url: '/umbraco/contentlock/api/v1/ContentGuard/Unlock/{key}'
        });
    }
    
}