// This file is auto-generated by @hey-api/openapi-ts

export type ContentLockOverview = {
    totalResults: number;
    items: Array<ContentLockOverviewItem>;
};

export type ContentLockOverviewItem = {
    key: string;
    nodeName: string;
    contentType: string;
    checkedOutBy: string;
    checkedOutByKey: string;
    lastEdited: string;
};

export type ContentLockStatus = {
    isLocked: boolean;
    lockedByKey: string;
    lockedByName?: string | null;
    lockedBySelf: boolean;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type BulkUnlockData = {
    body?: Array<string>;
    path?: never;
    query?: never;
    url: '/umbraco/contentlock/api/v1/BulkUnlock';
};

export type BulkUnlockErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type BulkUnlockError = BulkUnlockErrors[keyof BulkUnlockErrors];

export type BulkUnlockResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LockContentData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/contentlock/api/v1/Lock/{key}';
};

export type LockContentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type LockContentError = LockContentErrors[keyof LockContentErrors];

export type LockContentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LockOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/contentlock/api/v1/LockOverview';
};

export type LockOverviewErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type LockOverviewResponses = {
    /**
     * OK
     */
    200: ContentLockOverview;
};

export type LockOverviewResponse = LockOverviewResponses[keyof LockOverviewResponses];

export type StatusData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/contentlock/api/v1/Status/{key}';
};

export type StatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type StatusResponses = {
    /**
     * OK
     */
    200: ContentLockStatus;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type UnlockContentData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/contentlock/api/v1/Unlock/{key}';
};

export type UnlockContentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type UnlockContentError = UnlockContentErrors[keyof UnlockContentErrors];

export type UnlockContentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44391' | (string & {});
};