// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44378' | (string & {});
};

export type ContentLockOverviewItem = {
    key: string;
    nodeName: string;
    contentType: string;
    checkedOutBy: string;
    checkedOutByKey: string;
    lastEdited: string;
    lockedAtDate: string;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type IceServerResponse = {
    urls: Array<string>;
    username?: string | null;
    credential?: string | null;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type BulkUnlockData = {
    body?: Array<string>;
    path?: never;
    query?: never;
    url: '/umbraco/contentlock/api/v1/BulkUnlock';
};

export type BulkUnlockErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type BulkUnlockError = BulkUnlockErrors[keyof BulkUnlockErrors];

export type BulkUnlockResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LockContentData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/contentlock/api/v1/Lock/{key}';
};

export type LockContentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type LockContentError = LockContentErrors[keyof LockContentErrors];

export type LockContentResponses = {
    /**
     * OK
     */
    200: ContentLockOverviewItem;
};

export type LockContentResponse = LockContentResponses[keyof LockContentResponses];

export type GetTurnCredentialsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/contentlock/api/v1/TurnCredentials';
};

export type GetTurnCredentialsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Bad Gateway
     */
    502: unknown;
};

export type GetTurnCredentialsResponses = {
    /**
     * OK
     */
    200: Array<IceServerResponse>;
};

export type GetTurnCredentialsResponse = GetTurnCredentialsResponses[keyof GetTurnCredentialsResponses];

export type UnlockContentData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/contentlock/api/v1/Unlock/{key}';
};

export type UnlockContentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type UnlockContentError = UnlockContentErrors[keyof UnlockContentErrors];

export type UnlockContentResponses = {
    /**
     * OK
     */
    200: unknown;
};
