// This file is auto-generated by @hey-api/openapi-ts

export type ContentLockOverview = {
    totalResults: number;
    items: Array<(ContentLockOverviewItem)>;
};

export type ContentLockOverviewItem = {
    key: string;
    nodeName: string;
    contentType: string;
    checkedOutBy: string;
    checkedOutByKey: string;
    lastEdited: string;
};

export type ContentLockStatus = {
    isLocked: boolean;
    lockedByKey: string;
    lockedByName?: (string) | null;
    lockedBySelf: boolean;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type BulkUnlockData = {
    body?: Array<(string)>;
};

export type BulkUnlockResponse = (string);

export type BulkUnlockError = ((ProblemDetails) | unknown);

export type LockContentData = {
    path: {
        key: string;
    };
};

export type LockContentResponse = (unknown);

export type LockContentError = ((ProblemDetails) | unknown);

export type LockOverviewResponse = ((ContentLockOverview));

export type LockOverviewError = (unknown);

export type StatusData = {
    path: {
        key: string;
    };
};

export type StatusResponse = ((ContentLockStatus));

export type StatusError = (unknown);

export type UnlockContentData = {
    path: {
        key: string;
    };
};

export type UnlockContentResponse = (unknown);

export type UnlockContentError = ((ProblemDetails) | unknown);